namespace BM_RCON.BM_RCON_lib
{
    enum ViceID
    {
        lager = 0,
        cider = 1,
        ale = 2,
        moonshine = 3,
        red_wine = 4,
        whiskey = 5,
        smokes = 6,
        martini = 7,
        jagerbomb = 8,
        tequila = 9,
        cigar = 10,
        joint = 11,
        stout = 12,
        margarita = 13,
        vodka = 14,
        gin_tonic = 15,
        bloody_mary = 16,
        screwdriver = 17,
        sake = 18,
        rubbing_alcohol = 19,
        mead = 20,
        white_wine = 21,
        porter = 22,
        hot_wings = 23,
        energy_drink = 24,
        painkillers = 25,
        dyson_iced_tea = 26,
        hard_lemonade = 27,
        beer = 28,
        spliff = 29,
        stimulants = 30,
        absinthe = 31,
        rum = 32,
        champagne = 33,
        vape_pen = 34,
        sherry = 35,
        espresso = 36,
        antacids = 37,
        varian_cigar = 38,
        water
    }
}