namespace BM_RCON.BM_RCON_lib
{
    /// <summary>
    /// Enum for weapons ID (not all implemented yet)
    /// </summary>
    enum WeaponID
    {
        // to update when weapons will be there
        fists = 0,
        // nothing = 1,
        pistol = 2,
        silenced_pistol = 3,
        underwater_pistol = 4,
        revolver = 5,
        // nothing = 6,
        compact_pistol = 7,
        handcannon = 8,
        uzi = 9,
        compact_uzi = 10,
        // nothing = 11,
        light_smg = 12,
        smg = 13,
        power_smg = 14,
        // nothing = 15,
        sawn_off = 16,
        pump = 17,
        db = 18,
        trench = 19,
        // nothing = 20,
        light_ar = 21,
        assault_rifle = 22,
        keymaster = 23,
        heal_rifle = 24,
        underwater_rifle = 25,
        musket = 26,
        ak = 27,
        // nothing = 28,
        long_rifle = 29,
        lever = 30,
        plinger = 31,
        sniper = 32,
        bolt = 33,
        // nothing = 34,
        // nothing = 35,
        machine_gun = 36,
        // nothing = 37,
        gl = 38,
        heavy_gl = 39,
        // nothing = 40,
        rocket = 41,
        // nothing = 42,
        // nothing = 43,
        // nothing = 44,
        acid_gun = 45,
        // nothing = 46,
        muleslapper = 47,
        // nothing = 48,
        bow = 49,
        crossbow = 50,
        grapplehook = 51,
        knife = 52,
        sword = 53,
        wrench = 54,
        // nothing = 55,
        magic = 56,
        railgun = 57,
        // nothing = 58,
        // nothing = 59,
        // nothing = 60,
        drone = 61,
        fragnade = 62,
        // nothing = 63,
        emp = 64,
        molotov = 65,
        // nothing = 66,
        healnade = 67,
        gasnade = 68,
        flashbang = 69,
        skate = 70,
        // nothing = 71,
        suicide_vest = 72,
        // nothing = 73,
        pineapple = 74,
        scuba = 75,
        // nothing = 76,
        // nothing = 77,
        jetpack = 78,
        boomerang = 79
    }
}